# inventories/example/hosts.yml

all:
  hosts:
    dev-admin:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
  vars:
    app_env: example
    app_cert_issuer: "{{ acme_aws_prod_issuer }}"
    image_pull_policy: Always
    log_level: DEBUG
        
    # MetalLB
    # use_metal_lb: true

    # ACME
    acme_prod_email: "mail@example.com"
    acme_staging_email: "staging+mail@example.com"
    
    # SMTP
    smtp_host: email-smtp.example.com
    smtp_sender_email: mail@example.com

    # DB
    postgres_password: "{{ dev_postgres_password }}"
    replication_password: "{{ dev_replication_password }}"

    # Distributed Tracing
    otel_exporter_otlp_endpoint: "{{ dev_otel_exporter_otlp_endpoint }}"
    otel_exporter_otlp_headers: "{{ dev_otel_exporter_otlp_headers }}"
    otel_exporter_otlp_protocol: "http/protobuf"
    otel_traces_exporter: "otlp"
    otel_metrics_exporter: "otlp"
    otel_logs_exporter: "otlp"
    otel_log_level: "error"

    # Market Data Front-End App
    app_domain: mdp.example.com
    dashboard_password: "{{ dev_admin_password }}"
    mdp_app_image: "{{ dev_container_repo }}/kuhl-haus-mdp-app-server:{{ app_container_image_version }}"


    # Market Data Cache (Redis) variables
    mdc_server_domain: mdp-cache.example.com
    redis_password: "{{ dev_redis_password }}"

    # Market Data Listener
    mdl_server_domain: mdp-listener.example.com
    mdl_server_image: "{{ dev_container_repo }}/kuhl-haus-mdl-server:{{ app_container_image_version }}"
    market_data_listener_auto_start_enabled: "True"

    # Market Data Processor
    mdp_server_domain: mdp-processor.example.com
    mdp_server_image: "{{ dev_container_repo }}/kuhl-haus-mdp-server:{{ app_container_image_version }}"

    # Market Data Queues
    mdq_server_domain: mdp-queues.example.com
    rabbitmq_password: "{{ dev_rabbitmq_password }}"

    # Widget Data Service
    wds_server_domain: wds.example.com
    wds_server_image: "{{ dev_container_repo }}/kuhl-haus-wds-server:{{ app_container_image_version }}"
    wds_server_auth_enabled: "True"
    wds_server_auth_api_key: "{{ dev_wds_api_token }}"
